config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  get'/comments/index' => 'comments#index'
  get'/accounts/index' => 'accounts#index'
  get'/places/index' => 'places#index'
  resources :accounts
  resources :places
  resources :comments

  get '/login' => 'session#new'        # Sign in form
  post '/login' => 'session#create'    # Sign in action
  delete '/login' => 'session#destroy' # Sign out
  # See rails guide for routing, in particular nested routes
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id              :integer          not null, primary key
#  email           :text
#  display_name    :text
#  display_photo   :text
#  interests       :text
#  dob             :date
#  location        :text
#  hiking_ability  :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#

class Account < ApplicationRecord
  has_secure_password
  has_many :comments
  has_many :accounts, through: :comments
  belongs_to :comment, optional: true
  belongs_to :places, optional: true

  validates :email, :presence => true, :uniqueness => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  date       :text
#  content    :text
#  blog       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  place_id   :integer
#  account_id :integer
#

class Comment < ApplicationRecord
  belongs_to :place
  belongs_to :account
end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id         :integer          not null, primary key
#  name       :text
#  area       :text
#  length     :text
#  distance   :text
#  difficulty :text
#  one_way    :text
#  fee        :text
#  access     :text
#  conditions :text
#  safety     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Place < ApplicationRecord
  has_many :comments
  has_many :accounts, through: :comments
  belongs_to :comment, optional: true
  belongs_to :accounts, optional: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :require_login
  def new
    @account = Account.new
  end

  def index
    @account = Account.all
  end

  def edit
    unless @current_account.id == params[:id].to_i
      redirect_to accounts_path
    end
    @account  = Account.find params[:id]
  end

  def show
    if @current_account.nil?
      redirect_to root_path
    end
    @account = Account.find params[:id]
  end

  def update
    account = Account.find params[:id]
    account.update account_params
    redirect_to account
  end



  def create
    @account = Account.new account_params
    @account.display_photo = "/assets/avatar.png"
    @account.display_name = "Anonymous"
    if @account.save
      session[:account_id] = @account.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def account_params
    params.require(:account).permit(:email, :password, :password_confirmation, :display_name, :display_photo, :interests, :dob, :location, :hiking_ability)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :fetch_account

  before_action :require_login
  private
  def fetch_account
    @current_account = Account.find_by :id => session[:account_id] if session[:account_id].present?
    session[:account_id] = nil unless @current_account.present? # This prevents horrors if you reseed.
      def require_login
    unless @current_account
      redirect_to root_path
    end
  end
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find params[:id]
  end

  def index
    @comment = Comment.all
  end

  def show
    @comment = Comment.find params[:id]
  end

  def create
    comment = Comment.new comment_params
    comment.account_id = @current_account.id
    if comment.save
      redirect_to comment # it worked!
    else
      redirect_to new
    end
  end

  def update
    comment = Comment.find params[:id]
    comment.update comment_params
    redirect_to comment
  end

  def destroy
    unless @current_account.id == params[:id]
      redirect_to comments_path
    end
    comment = Comment.find params[:id]
    comment.destroy
    redirect_to comments_path
  end

  private
  def comment_params
    params.require(:comment).permit(:date, :content, :blog, :place_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :require_login
  def home
  end
end

app/controllers/places_controller.rb
# FIX THIS

class PlacesController < ApplicationController
  def new
    @place = Place.new
  end

  def edit
    @place = Place.find params[:id]
  end

  def index
    @place = Place.all
  end

  def show
    @place = Place.find params[:id]
  end

  def create
    place = Place.new place_params
    if place.save
      redirect_to place # it worked!
    else
      render :new
    end
  end

  def update
    place = Place.find params[:id]
    place.update place_params
    redirect_to place
  end

  def destroy
    place = Place.find params[:id]
    place.destroy
    redirect_to places_path
  end

  private
  def place_params
    params.require(:place).permit(:name, :area, :length, :distance, :difficulty, :one_way, :fee, :access, :conditions, :safety)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login
  def new
  end

  def create
    @account = Account.find_by :email => params[:email]
    if @account.present? && @account.authenticate(params[:password])
      session[:account_id] = @account.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:account_id] = nil
    redirect_to login_path
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>

  <%= f.label :display_name %>
  <%= f.text_field :display_name %>

  <%= f.label :display_photo %>
  <%= f.text_field :display_photo %>

  <%= f.label :interests %>
  <%= f.text_field :interests %>

  <%= f.label :dob, 'Date of birth' %>
  <%= f.text_field :dob %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :hiking_ability %>
  <%= f.text_field :hiking_ability %>

  <%= f.submit %>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit Avatar</h1>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<h1>Other Adventures</h1>

<% @account.each do |account| %>
    <ul>
      <% unless account.display_name == @current_account.display_name || account.display_name.nil? || account.display_name.empty? || account.display_name === "Anonymous"%>
      <li><a href="/accounts/<%=account.id%>"><%= account.display_name %> </a></li>
      <% end %>
    </ul>
<% end %>

app/views/accounts/new.html.erb
<h1>Sign Up</h1>

<% if @account.errors.any? %>
  <ol>
    <% @account.errors.full_messages.each do |msg| %>
    <div class="alert alert-primary" role="alert">
    <li><%= msg.capitalize %></li>
    </div>
    <% end %>
  </ol>
<% end %>


<div class="form-group">

  <%= form_for @account do |f| %>
    <%= f.label :email_address %>
    <%= f.email_field :email, :required => true, :class => "form-control", :placeholder => "name@example.com" %>

    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control" %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "form-control" %>

    <%= f.submit "Sign up!" %>
  </div>
<% end %>

app/views/accounts/show.html.erb
<dl class="row">
  <dt class="col-sm-3", id="accountname"><%= @account.display_name %></dt>
  <dt class="col-sm-9"></dt>
  <% unless @account.display_photo.nil? %>
  <dd class="col-sm-3", id="accountphoto"> <img class="img-fluid" src="<%=@account.display_photo%>">
  </dd>
  <% end %>
  <dt class="col-sm-9"></dt>

  <dt class="col-sm-3">Date of Birth</dt>
  <dd class="col-sm-9">
    <p><%= @account.dob %></p>
  </dd>
  <dt class="col-sm-3">Interests</dt>
  <dd class="col-sm-9">
    <p><%= @account.interests %></p>
  </dd>
  <dt class="col-sm-3">Hiking Ability</dt>
  <dd class="col-sm-9">
    <p><%= @account.hiking_ability %></p>
  </dd>
</dl>

  <% unless @account.comments.empty? %>
  <h2>Comments</h2>
  <% @account.comments.each do |comment| %>
  <div class="media">
  <img class="mr-3" src="<%@account.display_photo%>">
  <div class="media-body">
    <h5 class="mt-0"><%@account.display_name%></h5>
    <%comment.content%>
    <br>
    Date of trip <%comment.date%>
    <br>
    Relevant blog <%comment.blog%>
  </div>
</div>
  <% end %>
<% end %>
<a href="/accounts">Back</a>

<% if @current_account.id == params[:id].to_i %>
  <div class="controls">
    <%= link_to 'Edit account', edit_account_path(@account) %>
  </div>
<% else %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :blog %>
  <%= f.text_field :blog %>

  <%= f.label :place_id %>
  <%= f.select :place_id, Place.pluck(:name, :id), :include_blank => true %>

  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Comment temp</h1>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<h1>Comment</h1>

<% @comment.each do |comment| %>
    <ul>
      <li><%= comment.date %></li>
    </ul>
<% end %>

app/views/comments/new.html.erb
<h1>Add a Comment</h1>
<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<dl class="row">


  <dt class="col-sm-3">Date of visit</dt>
  <dd class="col-sm-9">
    <p><%=  @comment.date  %></p>
  </dd>
  <%if @comment.blog.present? %>
  <dt class="col-sm-3">My blog post</dt>
  <dd class="col-sm-9">
    <p><%= @comment.blog %></p>
  </dd>
  <% end %>
  <dt class="col-sm-3"></dt>
  <dd class="col-sm-9" id="commentcontent">
    <p><%= @comment.content %></p>
  </dd>
</dl>

<div class="controls">
  <% if @current_account.id == @comment.account_id %>
    <div class="controls">
      <%= link_to 'Edit comment', edit_comment_path(@comment.id) %>
      <%= link_to 'Delete comment', @comment, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>New South Trails</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Abel|Amatic+SC" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">New South Trails</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class= "navbar-nav">

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#"
                id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

              <% if @current_account.present? %>
                <a class="dropdown-item" data-method="delete" href="/login"> Sign-Out</a>
                <a class="dropdown-item" href="/accounts/<%=@current_account.id%>"> View Account </a>
              <% else %>
                <a class="dropdown-item" href="/accounts/new"> Sign-Up </a>
                <a class="dropdown-item" href="/login"> Log-In </a>
              <% end %>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    <%= yield %>
    <footer class="footer">
      <div class="container">
        <span class="text-muted"> Created for GA by Mackenzie Radinoff </span>
      </div>
    </footer>


  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4">

    <% if @current_account.present? %>
      <% if @current_account.display_name.present? && @current_account.display_name != "Anonymous"%>
        Welcome back <%= @current_account.display_name %> !
      <% else %>
      Welcome back <%= @current_account.email %> !
      <%end%>
    <% else %>
       Welcome
    <% end %>

  </h1>

  <p class="lead"> Ready for an Adventure!?
    <%if @current_account.present? %>
      Click the Links Below</p>
    <% else %>
    <span>Login to your Account</span>, then Click the Links Below
  <% end %>
  <hr class="my-4">
  <p class="lead">
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">About Us</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
        </div>
        <div class="modal-body">
          <p>Hiking is about expecting the unexpected, but the unexpected can
          get a little much sometimes... That's why we are here to foster a hiking
          community in NSW that let's hikers share info about the more tempermental details
          about a track, such as trail quality, tricky navigational points, and accesibility tips.
          Moreso our site allows hikers to upload trails that are a little bit under the radar.
          Have fun and safe travels~</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  </p>
</div>
<div class="container" id="home">
  <div class="row">
    <div class="col">
      <div class="card border-dark mb-3" id= "placeslink" style="max-width: 18rem;">
        <div class="card-header"><a class="placeslink" href="/places/index"> Places to Explore! </a></div>
        <div class="card-body text-dark">
          <p class="card-text">Plan your next hike, our inspire someone else to take your trail!</p>
        </div>
      </div>
      </div>
    <div class="col">
      <div class="card border-dark mb-3" id="peoplelink" style="max-width: 18rem;">
        <div class="card-header"><a class="accountslink" <%if @current_account.nil?%> href="/"> <%else%> href="/accounts/index"><%end%> Other Adventurers </a></div>
        <div class="card-body text-dark">
          <p class="card-text">Make your hiking community a little bigger!</p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>

  <%= f.label :area %>
  <%= f.text_field :area %>

  <%= f.label :length %>
  <%= f.text_field :length %>

  <%= f.label :distance %>
  <%= f.text_field :distance %>

  <%= f.label :difficulty %>
  <%= f.text_field :difficulty %>

  <%= f.label :one_way %>
  <%= f.text_field :one_way %>

  <%= f.label :fee %>
  <%= f.text_field :fee %>

  <%= f.label :access %>
  <%= f.text_field :access %>


  <%= f.submit %>
<% end %>

app/views/places/edit.html.erb
<h1>Edit Trail</h1>
<%= render :partial => 'form' %>

app/views/places/index.html.erb
<h1>Hiking Trails</h1>

<% @place.each do |place| %>
    <ul>
      <li><a href="/places/<%=place.id%>"> <%= place.name %> </a></li>
    </ul>
<% end %>
<a href="/places/new">Add Trail</a>

app/views/places/new.html.erb
<h1>Add a Trail</h1>
<%= render :partial => 'form' %>

app/views/places/show.html.erb
<dl class="row">
  <dt class="col-sm-3", id="placename"><%= @place.name %></dt>
  <dt class="col-sm-9"></dt>
  <dd class="col-sm-3", id="placearea"><%= @place.area %></dd>
  <dt class="col-sm-9"></dt>

  <dt class="col-sm-3">Estimated time needed</dt>
  <dd class="col-sm-9">
    <p><%= @place.length %></p>
  </dd>
  <dt class="col-sm-3">Distance of the trail (kilometres)</dt>
  <dd class="col-sm-9">
    <p><%= @place.distance %></p>
  </dd>
  <dt class="col-sm-3">Difficulty of the trail</dt>
  <dd class="col-sm-9">
    <p><%= @place.difficulty %></p>
  </dd>
  <dt class="col-sm-3">Is the trail a circuit?</dt>
  <dd class="col-sm-9">
    <p><%= @place.one_way %></p>
  </dd>
  <dt class="col-sm-3">Park fees</dt>
  <dd class="col-sm-9">
    <p><%= @place.fee %></p>
  </dd>
</dl>

<% unless @place.comments.empty? %>
  <h2>Comments</h2>
  <% @place.comments.each do |comment| %>
  <br>
  <div class="media">
  <img class="align-self-center mr-3" src="<%=comment.account.display_photo%>" alt="<%=comment.account.display_photo%>">
  <div class="media-body">
    <h5 class="mt-0"><%=comment.date%></h5>
    <p><%=comment.content%></p>
    <p class="mb-0"><%=comment.blog%></p>
  </div>
</div>

  <% end %>
<% end %>
<%= link_to 'Add Trail Notes', new_comment_path %>
<br>

<div class="controls">
  <%= link_to 'Edit place', edit_place_path(@place) %>
  <br>
  <%= link_to 'Delete place', @place, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
</div>

app/views/session/new.html.erb
<h1>Log in</h1>

<h2><%= flash[:error] %></h2>

<div class="form-group">

  <%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email, nil, :class => "form-control" %>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password, nil, :class => "form-control" %>
  <br>
  <%= submit_tag "Log in" %>
  <% end %>
</div>